### ISSUE TITLE
WebP format support

### ISSUE THREAD

**Issue by evolvens** [JamesHeinrich/phpThumb#107]
Why not add support for the WebP format?

Thank you!

**Comment by zikkuratvk** [comment]
WebP is a google requirement for page optimization, a very useful feature.

**Comment by JamesHeinrich** [comment]
This is untested, but give it a go: https://github.com/JamesHeinrich/phpThumb/commit/884abbdb1b045c16b58b9b3f0969d93e043a7b26
If you find problems, please reopen this thread.

**Comment by alvesdnelio** [comment]
Good afternoon
I would like to know if the girls took the images with the webp format in phpThumb ??

I downloaded the entire phpThumb 1.7.15 project and still proceeded with reading images with the webp.

Here is an attachment with print.

![Captura de tela de 2019-05-15 15-32-24](https://user-images.githubusercontent.com/12106318/57803582-c3443300-7726-11e9-88c9-0b5c9dc1172c.png)

**Comment by JamesHeinrich** [comment]
As the error message says:
> edit phpThumb.config.php and (temporarily) set
> $PHPTHUMB_CONG['disable_debug'] = false;
> to view the details of this error

**Comment by alvesdnelio** [comment]
phpThumb() v1.7.15-201902101903
http://phpthumb.sourceforge.net

phpThumb() version          = 1.7.15-201902101903
phpversion()                = 5.6.40-7+0~20190503101815.14+stretch~1.gbp1a44f9
PHP_OS                      = Linux
$_SERVER[SERVER_SOFTWARE]   = Apache/2.4.25 (Debian)
__FILE__                    = /var/www/html/nissanvianorte/phpThumb/phpthumb.class.php
realpath(.)                 = /var/www/html/nissanvianorte/phpThumb
$_SERVER[PHP_SELF]          = /nissanvianorte/phpThumb/phpThumb.php
$_SERVER[HOST_NAME]         = 
$_SERVER[HTTP_REFERER]      = 
$_SERVER[QUERY_STRING]      = src=fotos_bancoimagens/494.webp
$_SERVER[PATH_INFO]         = 
$_SERVER[DOCUMENT_ROOT]     = /var/www/html
getenv(DOCUMENT_ROOT)       = /var/www/html

get_magic_quotes_gpc()         = FALSE
get_magic_quotes_runtime()     = FALSE
error_reporting()              = integer     32767
ini_get(error_reporting)       = string(1)   "0"
ini_get(display_errors)        = string(1)   "1"
ini_get(allow_url_fopen)       = string(1)   "1"
ini_get(disable_functions)     = string(320) "pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,"
get_cfg_var(disable_functions) = string(320) "pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,"
ini_get(safe_mode)             = FALSE
ini_get(open_basedir)          = string(0)   ""
ini_get(max_execution_time)    = string(2)   "60"
ini_get(memory_limit)          = string(4)   "128M"
get_cfg_var(memory_limit)      = string(4)   "128M"
memory_get_usage()             = integer     432568

$this->config_prefer_imagemagick            = TRUE
$this->config_imagemagick_path              = NULL
$this->ImageMagickWhichConvert()            = 
[actual ImageMagick path used]              = string(0)   ""
file_exists([actual ImageMagick path used]) = FALSE
ImageMagickVersion(false)                   = 
ImageMagickVersion(true)                    = 

$this->config_cache_directory               = string(44)  "/var/www/html/nissanvianorte/phpThumb/cache/"
$this->config_cache_directory_depth         = integer     2
$this->config_cache_disable_warning         = FALSE
$this->config_cache_maxage                  = integer     2592000
$this->config_cache_maxsize                 = integer     10485760
$this->config_cache_maxfiles                = integer     200
$this->config_cache_force_passthru          = TRUE
$this->cache_filename                       = string(169) "/var/www/html/nissanvianorte/phpThumb/cache//8/87/phpThumb_cache_192.168.0.77__src87ae106abb5f2b5a1b71e54512396761_par52b4fbd9e2256843fcdbe9d1f35f2875_dat1557947766.jpeg"
is_readable($this->config_cache_directory)  = TRUE
is_writable($this->config_cache_directory)  = TRUE
is_readable($this->cache_filename)          = FALSE
is_writable($this->cache_filename)          = n/a

$this->config_document_root                  = string(13)  "/var/www/html"
$this->config_temp_directory                 = string(44)  "/var/www/html/nissanvianorte/phpThumb/cache/"
$this->config_output_format                  = string(4)   "jpeg"
$this->config_output_maxwidth                = integer     0
$this->config_output_maxheight               = integer     0
$this->config_error_message_image_default    = string(0)   ""
$this->config_error_bgcolor                  = string(6)   "CCCCFF"
$this->config_error_textcolor                = string(6)   "FF0000"
$this->config_error_fontsize                 = integer     1
$this->config_error_die_on_error             = TRUE
$this->config_error_silent_die_on_error      = FALSE
$this->config_error_die_on_source_failure    = TRUE
$this->config_nohotlink_enabled              = TRUE
$this->config_nohotlink_valid_domains        = <pre class='xdebug-var-dump' dir='ltr'> <small>/var/www/html/nissanvianorte/phpThumb/phpthumb.class.php:4024:</small> <b>array</b> <i>(size=1)</i>   0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'192.168.0.77'</font> <i>(length=12)</i> </pre>
$this->config_nohotlink_erase_image          = TRUE
$this->config_nohotlink_text_message         = string(38)  "Off-server thumbnailing is not allowed"
$this->config_nooffsitelink_enabled          = TRUE
$this->config_nooffsitelink_valid_domains    = <pre class='xdebug-var-dump' dir='ltr'> <small>/var/www/html/nissanvianorte/phpThumb/phpthumb.class.php:4024:</small> <b>array</b> <i>(size=1)</i>   0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'192.168.0.77'</font> <i>(length=12)</i> </pre>
$this->config_nooffsitelink_require_refer    = FALSE
$this->config_nooffsitelink_erase_image      = FALSE
$this->config_nooffsitelink_text_message     = string(29)  "Image taken from 192.168.0.77"
$this->config_high_security_enabled          = FALSE
$this->config_allow_src_above_docroot        = FALSE
$this->config_allow_src_above_phpthumb       = TRUE
$this->config_max_source_pixels              = float       22369621
$this->config_use_exif_thumbnail_for_speed   = FALSE
$this->config_border_hexcolor                = string(6)   "000000"
$this->config_background_hexcolor            = string(6)   "FFFFFF"
$this->config_ttf_directory                  = string(43)  "/var/www/html/nissanvianorte/phpThumb/fonts"
$this->config_disable_pathinfo_parsing       = TRUE
$this->config_disable_imagecopyresampled     = FALSE

$this->phpThumbDebug               = integer     9
$this->thumbnailQuality            = integer     75
$this->thumbnailFormat             = string(4)   "jpeg"
$this->gdimg_output                = NULL
$this->gdimg_source                = FALSE
$this->sourceFilename              = string(56)  "/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp"
$this->source_width                = NULL
$this->source_height               = NULL
$this->thumbnailCropX              = NULL
$this->thumbnailCropY              = NULL
$this->thumbnailCropW              = NULL
$this->thumbnailCropH              = NULL
$this->exif_thumbnail_width        = NULL
$this->exif_thumbnail_height       = NULL
$this->exif_thumbnail_type         = NULL
$this->thumbnail_width             = NULL
$this->thumbnail_height            = NULL
$this->thumbnail_image_width       = NULL
$this->thumbnail_image_height      = NULL
strlen($this->rawImageData)        = 0
strlen($this->exif_thumbnail_data) = 0

$this->src  = string(56)  "/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp"
$this->new  = NULL
$this->w    = FALSE
$this->h    = FALSE
$this->f    = string(0)   ""
$this->q    = integer     75
$this->sx   = NULL
$this->sy   = NULL
$this->sw   = NULL
$this->sh   = NULL
$this->far  = NULL
$this->bg   = NULL
$this->bc   = NULL
$this->file = NULL
$this->goto = NULL
$this->err  = NULL
$this->xto  = NULL
$this->ra   = NULL
$this->ar   = NULL
$this->aoe  = NULL
$this->iar  = NULL
$this->maxb = NULL

builtin_function_exists(exif_thumbnail)          = TRUE
builtin_function_exists(gd_info)                 = TRUE
builtin_function_exists(image_type_to_mime_type) = TRUE
builtin_function_exists(getimagesize)            = TRUE
builtin_function_exists(imagecopyresampled)      = TRUE
builtin_function_exists(imagecopyresized)        = TRUE
builtin_function_exists(imagecreate)             = TRUE
builtin_function_exists(imagecreatefromstring)   = TRUE
builtin_function_exists(imagecreatetruecolor)    = TRUE
builtin_function_exists(imageistruecolor)        = TRUE
builtin_function_exists(imagerotate)             = TRUE
builtin_function_exists(imagetypes)              = TRUE
builtin_function_exists(version_compare)         = TRUE
builtin_function_exists(imagecreatefromgif)      = TRUE
builtin_function_exists(imagecreatefromjpeg)     = TRUE
builtin_function_exists(imagecreatefrompng)      = TRUE
builtin_function_exists(imagecreatefromwbmp)     = TRUE
builtin_function_exists(imagecreatefromxbm)      = TRUE
builtin_function_exists(imagecreatefromxpm)      = TRUE
builtin_function_exists(imagecreatefromstring)   = TRUE
builtin_function_exists(imagecreatefromgd)       = TRUE
builtin_function_exists(imagecreatefromgd2)      = TRUE
builtin_function_exists(imagecreatefromgd2part)  = TRUE
builtin_function_exists(imagejpeg)               = TRUE
builtin_function_exists(imagegif)                = TRUE
builtin_function_exists(imagepng)                = TRUE
builtin_function_exists(imagewbmp)               = TRUE

gd_info.GD Version                         = string(5)   "2.2.5"
gd_info.FreeType Support                   = TRUE
gd_info.FreeType Linkage                   = string(13)  "with freetype"
gd_info.T1Lib Support                      = FALSE
gd_info.GIF Read Support                   = TRUE
gd_info.GIF Create Support                 = TRUE
gd_info.JPEG Support                       = TRUE
gd_info.PNG Support                        = TRUE
gd_info.WBMP Support                       = TRUE
gd_info.XPM Support                        = TRUE
gd_info.XBM Support                        = TRUE
gd_info.WebP Support                       = TRUE
gd_info.JIS-mapped Japanese Font Support   = FALSE

exif_info.EXIF Support               = string(7)   "enabled"
exif_info.EXIF Version               = string(51)  "1.4 $Id: cad29b729548e4206f0697710cc9e177f26fdff3 $"
exif_info.Supported EXIF Version     = string(4)   "0220"
exif_info.Supported filetypes        = string(9)   "JPEG,TIFF"

ApacheLookupURIarray() -- FAILED

$_GET[src]                           = string(30)  "../fotos_bancoimagens/494.webp"
$_GET[phpThumbDebug]                 = integer     9

$this->debugmessages:
  * phpThumb() v1.7.15-201902101903 in file "phpthumb.class.php" on line 229
  * setParameter(config_document_root, string(13)  "/var/www/html") in file "phpThumb.php" on line 162
  * setParameter(config_disable_debug, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_high_security_enabled, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_high_security_url_separator, string(1)   "&") in file "phpThumb.php" on line 162
  * setParameter(config_allow_src_above_docroot, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_allow_src_above_phpthumb, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_auto_allow_symlinks, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_additional_allowed_dirs, <pre class='xdebug-var-dump' dir='ltr'> <small>/var/www/html/nissanvianorte/phpThumb/phpthumb.class.php:4024:</small> <b>array</b> <i>(size=0)</i>   <i><font color='#888a85'>empty</font></i> </pre>) in file "phpThumb.php" on line 162
  * setParameter(config_cache_directory, string(44)  "/var/www/html/nissanvianorte/phpThumb/cache/") in file "phpThumb.php" on line 162
  * setParameter(config_cache_disable_warning, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_cache_directory_depth, integer     2) in file "phpThumb.php" on line 162
  * setParameter(config_cache_maxage, integer     2592000) in file "phpThumb.php" on line 162
  * setParameter(config_cache_maxsize, integer     10485760) in file "phpThumb.php" on line 162
  * setParameter(config_cache_maxfiles, integer     200) in file "phpThumb.php" on line 162
  * setParameter(config_cache_source_enabled, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_cache_source_directory, string(51)  "/var/www/html/nissanvianorte/phpThumb/cache/source/") in file "phpThumb.php" on line 162
  * setParameter(config_cache_source_filemtime_ignore_local, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_cache_source_filemtime_ignore_remote, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_cache_default_only_suffix, string(0)   "") in file "phpThumb.php" on line 162
  * setParameter(config_cache_prefix, string(28)  "phpThumb_cache_192.168.0.77_") in file "phpThumb.php" on line 162
  * setParameter(config_cache_force_passthru, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_temp_directory, string(44)  "/var/www/html/nissanvianorte/phpThumb/cache/") in file "phpThumb.php" on line 162
  * setParameter(config_prefer_imagemagick, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_imagemagick_use_thumbnail, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_imagemagick_path, NULL) in file "phpThumb.php" on line 162
  * setParameter(config_max_source_pixels, float       22369621) in file "phpThumb.php" on line 162
  * setParameter(config_output_format, string(4)   "jpeg") in file "phpThumb.php" on line 162
  * setParameter(config_output_maxwidth, integer     0) in file "phpThumb.php" on line 162
  * setParameter(config_output_maxheight, integer     0) in file "phpThumb.php" on line 162
  * setParameter(config_output_interlace, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_error_image_width, integer     400) in file "phpThumb.php" on line 162
  * setParameter(config_error_image_height, integer     100) in file "phpThumb.php" on line 162
  * setParameter(config_error_message_image_default, string(0)   "") in file "phpThumb.php" on line 162
  * setParameter(config_error_bgcolor, string(6)   "CCCCFF") in file "phpThumb.php" on line 162
  * setParameter(config_error_textcolor, string(6)   "FF0000") in file "phpThumb.php" on line 162
  * setParameter(config_error_fontsize, integer     1) in file "phpThumb.php" on line 162
  * setParameter(config_error_die_on_error, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_error_silent_die_on_error, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_error_die_on_source_failure, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_nohotlink_enabled, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_nohotlink_valid_domains, <pre class='xdebug-var-dump' dir='ltr'> <small>/var/www/html/nissanvianorte/phpThumb/phpthumb.class.php:4024:</small> <b>array</b> <i>(size=1)</i>   0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'192.168.0.77'</font> <i>(length=12)</i> </pre>) in file "phpThumb.php" on line 162
  * setParameter(config_nohotlink_erase_image, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_nohotlink_text_message, string(38)  "Off-server thumbnailing is not allowed") in file "phpThumb.php" on line 162
  * setParameter(config_nooffsitelink_enabled, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_nooffsitelink_valid_domains, <pre class='xdebug-var-dump' dir='ltr'> <small>/var/www/html/nissanvianorte/phpThumb/phpthumb.class.php:4024:</small> <b>array</b> <i>(size=1)</i>   0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'192.168.0.77'</font> <i>(length=12)</i> </pre>) in file "phpThumb.php" on line 162
  * setParameter(config_nooffsitelink_require_refer, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_nooffsitelink_erase_image, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_nooffsitelink_watermark_src, string(26)  "/demo/images/watermark.png") in file "phpThumb.php" on line 162
  * setParameter(config_nooffsitelink_text_message, string(29)  "Image taken from 192.168.0.77") in file "phpThumb.php" on line 162
  * setParameter(config_border_hexcolor, string(6)   "000000") in file "phpThumb.php" on line 162
  * setParameter(config_background_hexcolor, string(6)   "FFFFFF") in file "phpThumb.php" on line 162
  * setParameter(config_ttf_directory, string(43)  "/var/www/html/nissanvianorte/phpThumb/fonts") in file "phpThumb.php" on line 162
  * setParameter(config_http_user_agent, string(105) "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36") in file "phpThumb.php" on line 162
  * setParameter(config_disable_pathinfo_parsing, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_disable_imagecopyresampled, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_disable_onlycreateable_passthru, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_disable_realpath, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_http_fopen_timeout, integer     10) in file "phpThumb.php" on line 162
  * setParameter(config_http_follow_redirect, TRUE) in file "phpThumb.php" on line 162
  * setParameter(config_allow_local_http_src, FALSE) in file "phpThumb.php" on line 162
  * setParameter(config_use_exif_thumbnail_for_speed, FALSE) in file "phpThumb.php" on line 162
  * setParameter(src, string(30)  "../fotos_bancoimagens/494.webp") in file "phpThumb.php" on line 395
  * resolvePath: /var/www/html/nissanvianorte/phpThumb/../fotos_bancoimagens/494.webp (allowed_dirs: Array
(
)
) in file "phpthumb.class.php" on line 1176
  * resolvePath: iteration, path=/var/www/html/nissanvianorte/phpThumb/../fotos_bancoimagens/494.webp, base path = /var/www/html in file "phpthumb.class.php" on line 1195
  * open_basedir: "" in file "phpthumb.class.php" on line 1162
  * resolvePath: stop at component 9 in file "phpthumb.class.php" on line 1211
  * resolvePath: stop at path=/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp in file "phpthumb.class.php" on line 1214
  * resolvePath: path parsed, over in file "phpthumb.class.php" on line 1220
  * setSourceFilename(/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp) set $this->sourceFilename to "/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp" in file "phpthumb.class.php" on line 294
  * setParameter(phpThumbDebug, integer     9) in file "phpThumb.php" on line 395
  * $CanPassThroughDirectly="1" && $phpThumb->src="/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp" in file "phpThumb.php" on line 489
  * resolvePath: /var/www/html/nissanvianorte/fotos_bancoimagens/494.webp (allowed_dirs: Array
(
)
) in file "phpthumb.class.php" on line 1176
  * resolvePath: iteration, path=/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp, base path = /var/www/html in file "phpthumb.class.php" on line 1195
  * resolvePath: stop at component 7 in file "phpthumb.class.php" on line 1211
  * resolvePath: stop at path=/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp in file "phpthumb.class.php" on line 1214
  * resolvePath: path parsed, over in file "phpthumb.class.php" on line 1220
  * Not passing "/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp" through directly because getimagesize() failed in file "phpThumb.php" on line 562
  * $AvailableImageOutputFormats = array(text;ico;bmp;wbmp;gif;webp;png;jpeg) in file "phpthumb.class.php" on line 1005
  * $this->thumbnailFormat set to $this->config_output_format "jpeg" in file "phpthumb.class.php" on line 1016
  * $this->thumbnailQuality set to "75" in file "phpthumb.class.php" on line 1033
  * SetCacheFilename() _src set from md5($this->sourceFilename) "/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp" = "87ae106abb5f2b5a1b71e54512396761" in file "phpthumb.class.php" on line 3583
  * SetCacheFilename() _par set from md5(_dpi150_q75) in file "phpthumb.class.php" on line 3616
  * Cached file "/var/www/html/nissanvianorte/phpThumb/cache//8/87/phpThumb_cache_192.168.0.77__src87ae106abb5f2b5a1b71e54512396761_par52b4fbd9e2256843fcdbe9d1f35f2875_dat1557947766.jpeg" does not exist, processing as normal in file "phpThumb.php" on line 581
  * resolvePath: /var/www/html/nissanvianorte/fotos_bancoimagens/494.webp (allowed_dirs: Array
(
)
) in file "phpthumb.class.php" on line 1176
  * resolvePath: iteration, path=/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp, base path = /var/www/html in file "phpthumb.class.php" on line 1195
  * resolvePath: stop at component 7 in file "phpthumb.class.php" on line 1211
  * resolvePath: stop at path=/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp in file "phpthumb.class.php" on line 1214
  * resolvePath: path parsed, over in file "phpthumb.class.php" on line 1220
  * $this->sourceFilename set to "/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp" in file "phpthumb.class.php" on line 926
  * $this->cache_filename already set, skipping SetCacheFilename() in file "phpthumb.class.php" on line 3539
  * starting ExtractEXIFgetImageSize() in file "phpthumb.class.php" on line 3381
  * skipping getimagesize() because !is_null($this->getimagesizeinfo) in file "phpthumb.class.php" on line 3396
  * getimagesize("/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp") failed in file "phpthumb.class.php" on line 3420
  * $this->useRawIMoutput=true after checking $UnAllowedParameters in file "phpthumb.class.php" on line 1631
  * ImageMagickThumbnailToGD() aborting because ImageMagickCommandlineBase() failed in file "phpthumb.class.php" on line 2358
  * ImageMagickThumbnailToGD() failed in file "phpthumb.class.php" on line 3427
  * SetOrientationDependantWidthHeight() starting with ""x"" in file "phpthumb.class.php" on line 3360
  * SetOrientationDependantWidthHeight() setting w="0", h="0" in file "phpthumb.class.php" on line 3376
  * EXIF thumbnail extraction: (size=0; type=""; 0x0) in file "phpthumb.class.php" on line 3484
  * starting SourceImageToGD() in file "phpthumb.class.php" on line 3742
  * starting ImageCreateFromFilename(/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp) in file "phpthumb.class.php" on line 3657
  * empty $filename or getimagesize(/var/www/html/nissanvianorte/fotos_bancoimagens/494.webp) failed in file "phpthumb.class.php" on line 3706
  * Populating $rawimagedata in file "phpthumb.class.php" on line 3714
  * attempting ImageCreateFromStringReplacement($rawimagedata (340664 bytes), true) in file "phpthumb.class.php" on line 3728
  * ImageCreateFromStringReplacement() failed: unknown fileformat signature " 0x52 0x49 0x46" in file "phpthumb.class.php" on line 4316
  * Not using EXIF thumbnail data because $this->exif_thumbnail_data is empty in file "phpthumb.class.php" on line 3814
  * $this->gdimg_source is still empty in file "phpthumb.class.php" on line 3866
  * ImageMagickThumbnailToGD() failed in file "phpthumb.class.php" on line 3868
  * phpThumb() v1.7.15-201902101903
http://phpthumb.sourceforge.net

Unknown image type identified by "RIFF" ( 0x52 0x49 0x46 0x46) in SourceImageToGD() [3989] in file "phpthumb.class.php" on line 4189
  * SourceImageToGD() failed in file "phpthumb.class.php" on line 374
  * CleanUpCacheDirectory() set to purge (30.0 days; 10.00 MB; 200 files) in file "phpthumb.class.php" on line 744
  * CleanUpCacheDirectory() skipped because "/var/www/html/nissanvianorte/phpThumb/cache//phpThumbCacheStats.txt" is recently modified in file "phpthumb.class.php" on line 754
  * RenderOutput() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 448
  * RenderOutput [jpeg(/var/www/html/nissanvianorte/phpThumb/cache//8/87/phpThumb_cache_192.168.0.77__src87ae106abb5f2b5a1b71e54512396761_par52b4fbd9e2256843fcdbe9d1f35f2875_dat1557947766.jpeg)] failed in file "phpthumb.class.php" on line 629
  * Failed: RenderToFile(/var/www/html/nissanvianorte/phpThumb/cache//8/87/phpThumb_cache_192.168.0.77__src87ae106abb5f2b5a1b71e54512396761_par52b4fbd9e2256843fcdbe9d1f35f2875_dat1557947766.jpeg) in file "phpThumb.php" on line 681

$this->debugtiming:
  * 1557953002.712349 : phpThumb() constructor in file "phpthumb.class.php" on line 228
  * 1557953002.712262 : phpThumb.php start in file "phpThumb.php" on line 129
  * 1557953002.717411 : phpThumbDebug[0] in file "phpThumb.php" on line 221
  * 1557953002.717467 : phpThumbDebug[1] in file "phpThumb.php" on line 278
  * 1557953002.717585 : phpThumbDebug[2] in file "phpThumb.php" on line 380
  * 1557953002.718026 : phpThumbDebug[3] in file "phpThumb.php" on line 416
  * 1557953002.718105 : phpThumbDebug[4] in file "phpThumb.php" on line 483
  * 1557953002.718848 : phpThumbDebug[5] in file "phpThumb.php" on line 570
  * 1557953002.719148 : phpThumbDebug[6] in file "phpThumb.php" on line 586
  * 1557953002.719162 : phpThumbDebug[7] in file "phpThumb.php" on line 651
  * 1557953002.720864 : phpThumbDebug[8] in file "phpThumb.php" on line 661
  * 1557953002.721995 : phpThumbDebug[9] in file "phpThumb.php" on line 694
  * Total processing time: 0.009733

**Comment by alvesdnelio** [comment]
File in attachment
[phpThumbError.txt](https://github.com/JamesHeinrich/phpThumb/files/3184388/phpThumbError.txt)

**Comment by JamesHeinrich** [comment]
You need at least PHP v7.1.0 for WebP support using GD (your server is running PHP v5.6.40).
Alternately, you may be able to get WebP support if you install ImageMagick and make sure phpThumb is configured with the path (if it doesn't auto-detect).
