### ISSUE TITLE
php v8.0 issues?

### ISSUE THREAD

**Issue by dleffler** [JamesHeinrich/phpThumb#161]
Maybe it's my implementation, but phpThumb (always?) errors out in RenderOutput() as $this->gd_output is NOT a resource. Works in up to PHP v7.4.11 but (only) switching to PHP v8.0 it stops working...anyone else tested PHP v8.0?

**Comment by JamesHeinrich** [comment]
I have not tested it on PHP 8 (I don't currently have a PHP8 test environment). If you can find a more specific cause for the problem please post back here.

**Comment by modercol** [comment]
I had also the issues, the only one preventing me from uograding to php8 right now. 
The issues here is, that php changed the behavior of GD. Instead of a Ressource that is returned, it's an instance of \GDImage object.
According to this site https://php.watch/versions/8.0/GDImage (which is linked in the official Release announcement of php8), the solutionbis rather simple: Besides checking if the variable "is_resource" it is also necessary to check if variable is_object AND instance of \GDImage. This is According to the site fully BC.
Haven't looked into the phpthumb code as I just discovered it out yesterday. I'll give it a try tomorrow.

**Comment by dleffler** [comment]
I've given it a try and it seems to correct the problem...at least now I get the thumbnails under PHP v8. I don't know if I can get around to uploading a pull request.

**Comment by JamesHeinrich** [comment]
@dleffler if you can get around to submitting a PR that would be much appreciated.

**Comment by Ibochkarev** [comment]
Related https://github.com/JamesHeinrich/phpThumb/pull/162
