### ISSUE TITLE
eregi() is deprecated

### ISSUE THREAD

**Issue by timnolte** [JamesHeinrich/phpThumb#32]
When I have PHP error output turned on there are a lot of warnings about the use of eregi(). I will fork and provide a fix for these errors.

**Comment by JamesHeinrich** [comment]
You must be using a really old (pre-1.7.10) version since all ereg* functions were removed in v1.7.10 (24-Apr-2011):

https://github.com/JamesHeinrich/phpThumb/blob/master/docs/phpthumb.changelog.txt
v1.7.10 - April 24, 2011
  * replace all ereg* functions with preg* equivalents for PHP v5.3.0+ compatability

**Comment by timnolte** [comment]
Oops, OK, I was in the process of upgrading, and doing a git-base deployment and thought I had finished that. Apparently my development environment isn't using the latest code yet. Sorry.
