### ISSUE TITLE
Error: missing hash

### ISSUE THREAD

**Issue by leecollings** [JamesHeinrich/phpThumb#53]
Hey,

I'm trying to use the helper function to generate images (it worked with high_security disabled on my local copy), and that seemed to work fine.

When I turn on the high_security, and add a strong password, I attempted to use the helper function like so:

    <?php
            require_once('phpThumb/phpThumb.config.php');
            echo '<img src="'.htmlspecialchars(phpThumbURL('src='.$gallerySet->before_img.'&w=50', '/phpThumb/phpThumb.php')).'">';
    ?>

But I just receive `Error: missing hash`, even though the hash is displayed. (Excuse the screenshot, but it's the only way I can display the error message and the hash in the url to you)

![image](https://cloud.githubusercontent.com/assets/6681733/12924243/08ec0378-cf51-11e5-9b15-3f8dbd4e077a.png)

**Comment by JamesHeinrich** [comment]
Note the parameters in the url:
`phpThumb.php?src=/wp...jpg&w=50hash=cac8c9d2b2c77181e2528da3a32a0464`
Note that the parameters passed are "src" and "w", the latter not being just "50" but "50hash=cac8c9d2b2c77181e2528da3a32a0464" because the "&" separator indicating the start of the "hash" parameter is missing.

I believe this is related to your other issue https://github.com/JamesHeinrich/phpThumb/issues/52 where $PHPTHUMB_CONFIG['high_security_url_separator'] is empty, for whatever reason. Solve that and you should solve this as well.

**Comment by JamesHeinrich** [comment]
I have just discovered that sometime, I'm not sure exactly when, the config file definition was incorrectly entered as `$PHPTHUMB_CONFIG['config_high_security_url_separator']` instead of `$PHPTHUMB_CONFIG['high_security_url_separator']` -- the shorter version is the correct version, no "config_". Please check your config file and make sure the key is named correctly.
