### ISSUE TITLE
What is the error here?

### ISSUE THREAD

**Issue by leecollings** [JamesHeinrich/phpThumb#55]
The plugin was working fine, when all of a sudden the error images started appearing. So I debugged, and found an error (which I can't remember). It was saying the cache folder was unwriteable.

So I chown'd it to www-data, and refreshed the page. The folders and file were placed inside the cache folder but the error now seems to be this, which I don't understand what it's saying:

```
Unknown image type identified by "<br " ( 0x3c 0x62 0x72 0x20) in SourceImageToGD() [3850] in file "phpthumb.class.php" on line 4050
  * Deleting temp file "/var/www/html/phpThumb/cache/pThumbwwKB2H" in file "phpthumb.class.php" on line 248
  * SourceImageToGD() failed in file "phpthumb.class.php" on line 351
  * CleanUpCacheDirectory() set to purge (30.0 days; 10.00 MB; 200 files) in file "phpthumb.class.php" on line 667
  * CleanUpCacheDirectory() skipped because "/var/www/html/phpThumb/cache//phpThumbCacheStats.txt" is recently modified in file "phpthumb.class.php" on line 677
  * RenderOutput() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 425
  * RenderOutput [jpeg(/var/www/html/phpThumb/cache//7/78/phpThumb_cache_146.148.6.67__src78db10219ecbcca82c2491b9881ad02f_par82179c205cf1269d56360b59e27fb58d_dat0.jpeg)] failed in file "phpthumb.class.php" on line 561
  * Failed: RenderToFile(/var/www/html/phpThumb/cache//7/78/phpThumb_cache_146.148.6.67__src78db10219ecbcca82c2491b9881ad02f_par82179c205cf1269d56360b59e27fb58d_dat0.jpeg) in file "phpThumb.php" on line 611
```

**Comment by JamesHeinrich** [comment]
The first 4 bytes of your src are "<br ", which is clearly not an image file, sounds like some unexpected HTML output. Perhaps open the image source directly in your browser and see what's going on.

**Comment by leecollings** [comment]
Whatever it was, it seems to have fixed itself now. It sounds like it would have been the output of a display error.

**Comment by leecollings** [comment]
ONe more thing, something's happened where the php function for resizing seems to be halting on my mobile, and stops the rest of the code from loading resulting in the website not displaying correctly.

Is there any way to output to the screen any messages? I've tried turning on WP Debug, and that isn't displaying anything at the point the function is.

**Comment by leecollings** [comment]
HI James, not that I want to press you, but the issue with mobile is still happening, and there's nothing I can see to try and diagnose what's the issue. It's almost as though the PHP code is failing on mobile devices. Have you experienced this at all? You can view for yourself by visiting [http://146.148.6.67/](url). The Before & After on the sidebar, those images are phpThumb, and display on a desktop okay, but halt the page loading when viewed on a mobile, leaving the rest of the page unloadable.

Would you be kind enough to just have a look and test this for yourself?

**Comment by JamesHeinrich** [comment]
That IP doesn't load anything at all for me (no web page, doesn't even ping) so I can't comment.

I haven't seen anything mobile-specific, but I also very rarely use a mobile device.
But I'm not really sure how it could be a mobile vs desktop issue in relation to phpThumb, which generates a JPEG (typically) image file *server-side* from a URL, as long as the same URL is passed you should get the same image back no matter what platform you're calling it from.

You describe the page loading being broken at the point of the image, which is also unexpected, since phpThumb.php is called asynchronously as an <img> src and always (unless in debug mode) returns as an image, but even if it returned something broken it should not prevent the loading of the rest of the web page.

Try opening the phpThumb.php url directly in your mobile device browser and confirm your thumbnail is loading correctly.
Try temporarily commenting out phpThumb images entirely at the point you suspect they're breaking your page: leave the <img> tag there but replace the src with a known static image file or even just empty string - if the page loads (minus the image) then you can debug further with the specific image being loaded; if it's still broken then you know the problem is elsewhere.
