### ISSUE TITLE
How to set expiry for using with W3 Total Cache and Page Speed Insights

### ISSUE THREAD

**Issue by leecollings** [JamesHeinrich/phpThumb#56]
Hi James,

Great plugin! Quick question though, because these images are no longer images and are in fact PHP files, when running a Google Page Speed Insights test, all the images flag up as having no expiry date in the HTTP headers.

I have W3 Total Cache installed, which sets expiry dates for all media files, but obviously these aren't seen as media files and are not touched.

Is there anything in your plugin files that can set an expiry date, and not have the 24 hours, as Google Page Speed Insights is reporting?

![pagespeed insights](https://cloud.githubusercontent.com/assets/6681733/13045490/86599c20-d3cb-11e5-9016-a961586be487.png)

**Comment by JamesHeinrich** [comment]
Since the commit from issue https://github.com/JamesHeinrich/phpThumb/pull/50 about 2 weeks ago the expiry date is configurable as `config_cache_maxage`.

Also, other than the URL it's called by, the returned thumbnail is very much an image, not a PHP file. The assorted headers (including Content-Type) are sent in [phpThumb.php around lines 76-90](https://github.com/JamesHeinrich/phpThumb/blob/master/phpThumb.php#L76-L90).

**Comment by leecollings** [comment]
Hi James,

I really appreciate your advice and help, but I'm not sure this is working quite right. I found the cache_maxage in the config file and increased the value, so it now reads `$PHPTHUMB_CONFIG['cache_maxage'] = 604800 * 30;`

Then, after deleting all the contents of the cache folder, I re-ran Page Speed insights, but this still displayed the same value (24 hours). So then I had a look using Fiddler, and saw that under the phpThumb images, it doesn't look like any cache is being set... strangely.

![bv-phpthumb-cache](https://cloud.githubusercontent.com/assets/6681733/13107606/6a74765a-d566-11e5-8ad4-71423ba82160.jpg)

Is there anything else in the config that I might need to do, or check?

PS, apologies on the IP not working, I am running this on Google Cloud, and my free trial ended. The new ip is now http://146.148.112.239/

**Comment by JamesHeinrich** [comment]
Looking at the returned headers (e.g. using [Rex Swain's HTTP Viewer](http://www.rexswain.com/httpview.html)) from [one](http://146.148.112.239/phpThumb/phpThumb.php?src=/wp-content/uploads/before-after/lip-enhancement_1_b.jpg&w=120&hash=d5c3cd97618b0544ad0033c7d5ae197a) of the thumbnails on your site I see
```
HTTP/1.1 200 OK
Date: Wed, 17 Feb 2016 13:13:43 GMT
Server: Apache/2.4.10 (Debian)
Content-Disposition: inline; filename="phpThumb_generated_thumbnail.jpeg"
Cache-Control: max-age=604800
Expires: Wed, 24 Feb 2016 13:13:43 GMT
Connection: close
Content-Type: image/jpeg
```
Which seems to be as expected, note the "Expires" and "Cache-Control: max-age" lines.

**Comment by leecollings** [comment]
Take a look at the result in a google page speed insight test, every search
I am getting, the images are being returned with a 24 hour expiry time,
even after emptying the cache folder.

Regards,

*Lee*

**Comment by JamesHeinrich** [comment]
Testing with Google PageSpeed Insight from your server seems to behave as you say, reporting that it's only cached for 24 hours. However testing a similar thing on my server shows no such problem, I'm not sure why.

What happens if you change [phpThumb.php line 76](https://github.com/JamesHeinrich/phpThumb/blob/master/phpThumb.php#L76) from
`header('Cache-Control: private');`
to
`header('Cache-Control: max-age='.$phpThumb->getParameter('config_cache_maxage'));`
Does that give any change/improvement?

**Comment by leecollings** [comment]
Hi James,

Although it was line 85 in my file, this seems to have resolved the issue
with Google Page Speed, thanks for that.

Regards,

*Lee*

**Comment by JamesHeinrich** [comment]
Actually I have discovered that the 'Expires:' date format may be incorrect, `DATE_RFC822` should be `DATE_RFC1123`. Major difference is 2-digit vs 4-digit year representation.

**Comment by leecollings** [comment]
Would this require a global update to the project, or is this just
individual to my case?

Regards,

*Lee*

**Comment by JamesHeinrich** [comment]
No, it's global, updated in https://github.com/JamesHeinrich/phpThumb/commit/1ccb3d5a3b0dec5f46c47ce220d22f5af014f5b5 but I mentioned it specifically since it may affect your issue.
