### ISSUE TITLE
Can't put thumbnail into a frame.

### ISSUE THREAD

**Issue by x-yuri** [JamesHeinrich/phpThumb#64]
Here are the params:

```
    'src' => '/img/1.png',
    'w' => 56,
    'h' => 56,
    'zc' => 1,
    'f' => 'png',
    'fltr' => [
        'ric|28|28',
        'over|/img/2.png|1|8',
    ],
```

or as a string: `src=%2Fimg%2F1.png&w=56&h=56&zc=1&f=png&fltr%5B0%5D=ric%7C28%7C28&fltr%5B1%5D=over%7C%2Fimg%2F2.png%7C1%7C8`

original image (`1.png`):
![1](https://cloud.githubusercontent.com/assets/730588/15789684/3aca30ec-29d6-11e6-9c3f-2dd484f8718a.png)

frame (`2.png`):
![2](https://cloud.githubusercontent.com/assets/730588/15789685/3aca3d26-29d6-11e6-81fa-623ef1b081af.png)

result:
![phpthumb_generated_thumbnail](https://cloud.githubusercontent.com/assets/730588/15789683/3ac97242-29d6-11e6-803b-4b41717d0cb0.png)

What I don't like above is the black corners sticking out of the frame, apparently. Initially, original image was a jpeg, so I thought it had to do with this. But turning it into png didn't help much. Am I doing anything wrong? Can this be dealt with in any way? Or at least, what's happening here, so that I could hopefully find some workaround?

**Comment by JamesHeinrich** [comment]
Your mask appears to be a white circle on a transparent background.
The phpThumb overlay mask works on black (transparent) to white (opaque):
http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x31

**Comment by x-yuri** [comment]
First, the frame has also a shadow.

Second, can you elaborate? I'd understand if you'd suggested to put a mask on the result, but that would cut off the shadow. But from what you're saying it looks like `over` filter does some masking. Can you tell in more words how it works? I don't understand the result I'm getting.

And also, adding black layer behind the frame, eliminating the shadow in the process, (basically, filling outer parts of `2.png` with black color) didn't help much, I can see them in the resulting image as well.

**Comment by JamesHeinrich** [comment]
The whiteness of the mask is used as an alpha channel. Anything that is 100% black will be transparent; anything that is 100% white will be the source image; anything gray between black and white will be a transparent version of the source image.
The 3 samples at http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x31 should illustrate the behaviour.
Remember of course that transparent output is only available for PNG output, JPEG output will be flattened to the background colour (you can set `bg` as shown in the 3rd example).

**Comment by x-yuri** [comment]
Um, what is mask I understand, I don't understand what `mask` filter has to do with `over` filter? I'm not applying `mask` filter, I'm applying **`over`** filter.

**Comment by JamesHeinrich** [comment]
Sorry, I misunderstood you regarding mask vs overlay.

I think rather than trying to underlay a white disc under the image it would work better to overlay a transparent-middle white ring to cover the edge of the image.

Also using the "elip" filter would probably work better than using "ric".

I have just made a small change (https://github.com/JamesHeinrich/phpThumb/commit/33cf5d5647bd957dd74a385b9ac26914fe545dce) to allow negative margins which helps with this situation.

Called as:
`/phpThumb.php?src=1.png&w=200&h=200&zc=1&f=png&fltr[]=over|3.png|0|-5&fltr[]=elip`
I get:
![out](https://cloud.githubusercontent.com/assets/3483435/16131996/3342ca88-33df-11e6-973b-08ce7e253676.png)
using this overlay:
![3](https://cloud.githubusercontent.com/assets/3483435/16132000/3a790a60-33df-11e6-9d91-3956c589e4e6.png)
(both of which naturally show up poorly because this page has a white background, but they're there.
